version: '3.7'

services:

  db: 
    container_name: mysql
    image: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    ports:
      - 3307:3306
    volumes:
      - mysql_data:/my/own/datadir
    networks:
      - backend
  
volumes:
  mysql_data:

networks:
  backend: